### ISSUE TITLE
Roblox fps unlocker doesnt work

### ISSUE THREAD

**Issue by LithRakoon** [Thelolguy1/grapejuice-flatpak#11]
When enabling Roblox fps unlocker and starting a game the application will crash
![image](https://user-images.githubusercontent.com/41258148/173236503-53ec15b5-a548-4c1b-b6c3-66a5f83da91e.png)

**Comment by Thelolguy1** [comment]
Okay, after talking to some other grapejuice users, it seems that wine 7.7 does not support the unlocker. I'll create a build with 7.2 tonight.

**Comment by Thelolguy1** [comment]
Please try the new wine72test branch.

**Comment by LithRakoon** [comment]
it functions! nicely done
