### ISSUE TITLE
Doesn't launch

### ISSUE THREAD

**Issue by ASOwnerYT** [Thelolguy1/grapejuice-flatpak#16]
After an (almost) fresh install of Fedora 36 and this flatpak, it has [this error](https://gist.github.com/ASOwnerYT/7d3506dabfd5c5778c94484bb7499098) when I try to launcher Roblox player or Studio.
![Screenshot from 2022-06-18 16-25-50](https://user-images.githubusercontent.com/23545044/174422667-93e965c8-e1fe-4d76-a810-d6672f80b0c9.png)

I've only just installed Fedora 36 yesterday on my ASUS TUF Gaming FX505DD laptop with an Nvidia GPU. I cloned this Github repository and used the install.sh script.

**Comment by LithRakoon** [comment]
do you have the nouveau driver or the proprietary driver installed?

**Comment by Thelolguy1** [comment]
Known issue, this is caused by a lack of GL32. Currently, you can try installing

```
flatpak install org.freedesktop.Platform/x86_64/21.08
flatpak install app/org.winehq.Wine/x86_64/stable-21.08
```

or you can wait until I add a patch for it.

**Comment by ASOwnerYT** [comment]
> do you have the nouveau driver or the proprietary driver installed?

I have the proprietary Nvidia drivers installed.

I'll try Thelolguy1's solution when I have access to my PC :)

**Comment by Thelolguy1** [comment]
I'm going to assume this is solved, considering there haven't been new messages in this thread.

**Comment by Thelolguy1** [comment]
Solved by latest push.
