### ISSUE TITLE
Studio locks up while attempting to log in.

### ISSUE THREAD

**Issue by FazlyMR** [Thelolguy1/grapejuice-flatpak#18]
Even after reinstalling grapejuice-flatpak and clearing the ~/.var/app/com.gitlab.brinkervii.grapejuice folder repeatedly, can't log into Studio as after I press "Log in" and it confirms the username and password are correct, which then it opens a browser tab going to Roblox which then should return to Roblox Studio to complete the log-in attempt but it locks up on that last part.

Forcing Studio to close by killing the process of course works, but log in still failed.

Using Fedora Silverblue 36, have installed all necessary Flatpak dependencies such as Wine, though I did install the non-Flatpak Grapejuice before but uninstalled it prior to trying out the Flatpak fork.

**Comment by Thelolguy1** [comment]
If I recall correctly, this is an issue with Grapejuice itself (due to some technical mumbo-jumbo with captcha). You'll need to open studio by navigating to a game you own, clicking the three dots in the upper right corner, and clicking edit.

**Comment by Thelolguy1** [comment]
Unless there is a change upstream, or the situation changes, I'll be closing this issue.
