### ISSUE TITLE
starting grapejuice flatpak missing wine error

### ISSUE THREAD

**Issue by LithRakoon** [Thelolguy1/grapejuice-flatpak#2]
hello!
just to note im not a very good tester but ill try my best to write up bug reports to improve this application!

i have installed the grapejuice flatpak which went quite well,
now i am trying to run <code>flatpak run com.gitlab.brinkervii.grapejuice app</code> to run grapejuice
now the app seems to starts correctly, but it seems that the grapejuice application doesnt have acces to the directory holding wine "/bin" since this application is sandboxed.

log + picture:
https://hastebin.skyra.pw/inuxejufoj.py
![image](https://user-images.githubusercontent.com/41258148/166802013-a482dc4a-f647-48f0-bc01-7b221452321e.png)

couple sollutions i could think of
1. add detection for the flatpak version of wine (and make it a dependency)
2. add a detection for versions of wine stored in places like "\~/.local/share/lutris/runners/wine/" and "~/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/"
but considering that roblox needs the mouse patch this would only be temporary sollution

**Comment by Thelolguy1** [comment]
Thanks for trying out my Flatpak and for your great testing feedback. I am aware of the issue with the missing wine; Brinker's patched wine is in the process of being repackaged into the Flatpak, so it will take a bit of time.

**Comment by Thelolguy1** [comment]
Hello @LithRakoon , I have recently pushed wine integration to the implement-wine branch. Please let me know if it works.

**Comment by LithRakoon** [comment]
Hey!
testing it it seem wine is working but im having some problems running <code>flatpak run com.gitlab.brinkervii.grapejuice app</code>,
it seems to initialize the patched wine and asks to install mono, which shouldnt be the case since i just asked to open the grapejuice application itself.
after the wine initialization is done it will install the roblox player which again it shouldnt do since i asked to to open the grapejuice application.
and after all thats done it wont open the grapejuice application itself it will return with this wine error
![image](https://user-images.githubusercontent.com/41258148/167389961-abf82e64-12ef-4d8e-805b-2fffbbb03060.png)

**Comment by LithRakoon** [comment]
also it seems that grapejuice logs arent saved because it doesnt have acces to ~./local/var

**Comment by Thelolguy1** [comment]
Thanks for your testing, I'll be looking into the problem.

**Comment by Thelolguy1** [comment]
This is a pretty complex issue so this might take some more time, sorry!

**Comment by Thelolguy1** [comment]
Initial problem was solved by recent PR, but I'll open a new issue regarding Roblox Player issues.
