### ISSUE TITLE
Unable to load summary from remote grapejuiceTest.

### ISSUE THREAD

**Issue by Coolcool4skool** [Thelolguy1/grapejuice-flatpak#22]
I tried to intsall this and got this code.

"Unable to load summary from remote grapejuiceTest: Remote listing for grapejuiceTest not available; server has no summary file. Check the URL passed to remote-add was valid."

I don't know if im just a idiot or what but I'm extremely new to linux and have no clue what im doing. Tips greatly accepted.

**Comment by lunarlattice0** [comment]
You need to git clone / download this repo before running the install.sh script. Additionally, I'm about to open a PR with flathub, so if possible, I would wait a bit for the official flathub release.

**Comment by lunarlattice0** [comment]
Please install this flatpak through

`flatpak install net.brinkervii.grapejuice`
