### ISSUE TITLE
Is this project discontinued?

### ISSUE THREAD

**Issue by Ma0us** [Thelolguy1/grapejuice-flatpak#3]
Is this project discontinued? There hasn't been any updates in almost 3 weeks.

**Comment by Thelolguy1** [comment]
@Ma0us No, not at all. There has been a lot more progress in the implement-wine branch. However, I am a bit stuck on #2 due to issues with Roblox's VMProtect. You can follow the development on the Grapejuice discord.

**Comment by Thelolguy1** [comment]
As an update, Roblox Studio does work now

**Comment by LithRakoon** [comment]
Roblox studio does seem to install and start correctly good job!
I am having a problem with logging in tho, when i log in on the studio application it opens the browser and tells me itll log me in but what i get is nothing itll just stay loading infinitely

**Comment by Thelolguy1** [comment]
That's an issue with grapejuice itself, not a flatpak bug. I'll check with the grapejuice discord and will let you know how to fix it

**Comment by Thelolguy1** [comment]
@LithRakoon Fixed, please run grapejuice's gui using `flatpak run com.gitlab.brinkervii.grapejuice grapejuice gui` or `flatpak run com.gitlab.brinkervii.grapejuice grapejuice-gui` and login to your account first, before launching studio.

**Comment by LithRakoon** [comment]
that commands do not exist, there is no GUI option only these:   
  app
  first-time-setup
  player
  studio
  top
  uninstall
and none of these open a GUI

**Comment by Thelolguy1** [comment]
@LithRakoon Try using `grapejuice-gui`, it should work. Additionally, `grapejuice gui` is an unlisted command

**Comment by LithRakoon** [comment]
![image](https://user-images.githubusercontent.com/41258148/171354681-d354d203-ef60-4cde-8fa2-4066aa8ee6d3.png)

**Comment by Thelolguy1** [comment]
@LithRakoon The command is `flatpak run com.gitlab.brinkervii.grapejuice gui`

**Comment by LithRakoon** [comment]
oh lol im stupid thank you

**Comment by Thelolguy1** [comment]
Yes, that's because the .desktop files haven't been implemented yet. I'll write them ASAP.

**Comment by Thelolguy1** [comment]
@LithRakoon I've implemented the .desktop files so you should now be able to launch it from KDE, GNOME, or whatever launcher you use. Additionally, this should permit logging in.

**Comment by LithRakoon** [comment]
awesome that works now great job!
