### ISSUE TITLE
Roblox Player fails to start

### ISSUE THREAD

**Issue by Thelolguy1** [Thelolguy1/grapejuice-flatpak#5]
Continued from #2 
![image](https://user-images.githubusercontent.com/18731514/170898190-a1f2a92c-6fe4-4e26-b112-d85f06ea6967.png)
Roblox Player fails to start, due to issues with VMProtect.

**Comment by Thelolguy1** [comment]
With the help of another user in the Grapejuice Discord, I've been able to confirm that the flathub org.winehq.wine flatpak CAN run Roblox. Work on this flatpak will resume shortly. 

![image](https://user-images.githubusercontent.com/18731514/172973675-d321c766-e398-406c-9f50-5fa9646570ce.png)

**Comment by Thelolguy1** [comment]
New Issue: Roblox Player can only progress to a white screen.

**Comment by LithRakoon** [comment]
seems this issue can be closed

[image](https://user-images.githubusercontent.com/41258148/173240449-aa5e62e9-c315-4e60-b0c8-73d9e8497a5a.png)
